# Generated by Django 4.1.4 on 2022-12-17 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='', max_length=255)),
                ('main_paragraph', models.TextField()),
                ('overview_title', models.CharField(default='', max_length=255)),
                ('overview_img_desc', models.CharField(default='', max_length=255)),
                ('overview_img', models.ImageField(upload_to='upload/')),
                ('calories_img_desc', models.CharField(default='', max_length=255)),
                ('calories_img', models.ImageField(upload_to='upload/')),
                ('body_measurements_img_desc', models.CharField(default='', max_length=255)),
                ('body_measurements_img', models.ImageField(upload_to='upload/')),
                ('about_title', models.CharField(default='', max_length=255)),
                ('about_paragraph', models.TextField(default='')),
                ('sevices_title', models.CharField(default='', max_length=255)),
                ('sevices_paragraph', models.TextField(default='')),
                ('s1_title', models.CharField(default='', max_length=255)),
                ('s1_paragraph', models.TextField(default='')),
                ('s2_title', models.CharField(default='', max_length=255)),
                ('s2_paragraph', models.TextField(default='')),
                ('s3_title', models.CharField(default='', max_length=255)),
                ('s3_paragraph', models.TextField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
